#!/usr/bin/env bash
# Install webserver nginx and print "Hello World!"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
