#!/usr/bin/env bash
#Installs Ngninx with the following config
#Listens on port 80
#Returns a page containing "Hello world!"
#Configures /redirect_me as a "301 moved permanently"
#Includes a custom 404 page containing 'Ceci n'est pas une page"
#Contains a custom HTTP header named X-Served-By. Value is hostname of running

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '$a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '/:80 default_server;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
