#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy

# Create a backup of the original HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Edit the HAProxy configuration
config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend back

backend back
    balance roundrobin
    server 294762-web-01 52.86.193.42:80 check
    server 294762-web-02 52.86.161.66:80 check
"

echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo systemctl enable haproxy

sudo service haproxy restart
