#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.

while  IFS=":" read -r username password uid gid info homedir shell
do
	user_id_info="${info%,*}"
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd
