#!/usr/bin/env bash
#loops from 1 to 10 and displays 'bad luck' for 4th iteration, 'good luck' for 8th iteration and 'Best schoool' for other iterations

i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
